spring.application.name=change-request-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/change_request_db
spring.datasource.username=postgres
spring.datasource.password=Hung@7410

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080